name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout Repository

    - uses: actions/setup-buildx-action@v1
      name: Build the Docker image

    - uses: actions/login-action@v2
      name: Login Docker Hub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: docker/build-push-action@v2
      name: Docker Push
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/hello-world-app:latest
        
    
